//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    
    public partial class GenExcel_select_contract_Result1
    {
        public string contract_id { get; set; }
        public string comment { get; set; }
        public string day_contract { get; set; }
        public string day_end { get; set; }
    }
}
