//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    
    public partial class GenExcel_select_document_period_Result2
    {
        public Nullable<int> project_ID { get; set; }
        public string doc { get; set; }
        public string type { get; set; }
        public string number { get; set; }
        public string period { get; set; }
    }
}
