//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    
    public partial class GenExcel_select_period_detail_Result2
    {
        public Nullable<int> project_id { get; set; }
        public Nullable<int> period { get; set; }
        public string money { get; set; }
        public string percent_money { get; set; }
        public Nullable<int> day_period { get; set; }
        public string date_period { get; set; }
        public string detail { get; set; }
    }
}
