//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NHADATABASEEntities1 : DbContext
    {
        public NHADATABASEEntities1()
            : base("name=NHADATABASEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int Committee_Delete(Nullable<int> project_id, Nullable<int> uid)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Committee_Delete", project_idParameter, uidParameter);
        }
    
        public virtual int Committee_insert(Nullable<int> project_id, Nullable<int> user_id, string com_position, string position)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var com_positionParameter = com_position != null ?
                new ObjectParameter("com_position", com_position) :
                new ObjectParameter("com_position", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("position", position) :
                new ObjectParameter("position", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Committee_insert", project_idParameter, user_idParameter, com_positionParameter, positionParameter);
        }
    
        public virtual ObjectResult<Committee_Select_check_Result3> Committee_Select_check(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Committee_Select_check_Result3>("Committee_Select_check", pidParameter);
        }
    
        public virtual ObjectResult<Committee_Select_employ_Result3> Committee_Select_employ(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Committee_Select_employ_Result3>("Committee_Select_employ", pidParameter);
        }
    
        public virtual ObjectResult<Concussion_Result3> Concussion(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Concussion_Result3>("Concussion", project_idParameter);
        }
    
        public virtual ObjectResult<GenExcel_select_contract_Result3> GenExcel_select_contract(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenExcel_select_contract_Result3>("GenExcel_select_contract", project_idParameter);
        }
    
        public virtual ObjectResult<GenExcel_select_document_period_Result3> GenExcel_select_document_period(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenExcel_select_document_period_Result3>("GenExcel_select_document_period", project_idParameter);
        }
    
        public virtual ObjectResult<GenExcel_select_period_detail_Result3> GenExcel_select_period_detail(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenExcel_select_period_detail_Result3>("GenExcel_select_period_detail", project_idParameter);
        }
    
        public virtual int Get_Project_State(Nullable<int> project_id, Nullable<int> state, ObjectParameter result)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Get_Project_State", project_idParameter, stateParameter, result);
        }
    
        public virtual ObjectResult<Get_TOR_Approve_Result3> Get_TOR_Approve(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_TOR_Approve_Result3>("Get_TOR_Approve", project_idParameter);
        }
    
        public virtual int Insert_Contract(Nullable<int> project_id, string contract_num, string date, string comment, string dateStart, string dateEnd, string employee, Nullable<int> period, Nullable<decimal> money)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var contract_numParameter = contract_num != null ?
                new ObjectParameter("contract_num", contract_num) :
                new ObjectParameter("contract_num", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var dateStartParameter = dateStart != null ?
                new ObjectParameter("dateStart", dateStart) :
                new ObjectParameter("dateStart", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            var employeeParameter = employee != null ?
                new ObjectParameter("employee", employee) :
                new ObjectParameter("employee", typeof(string));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(int));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Contract", project_idParameter, contract_numParameter, dateParameter, commentParameter, dateStartParameter, dateEndParameter, employeeParameter, periodParameter, moneyParameter);
        }
    
        public virtual int Insert_Installement(Nullable<int> contractnum, Nullable<int> project_id, Nullable<decimal> money, string period)
        {
            var contractnumParameter = contractnum.HasValue ?
                new ObjectParameter("contractnum", contractnum) :
                new ObjectParameter("contractnum", typeof(int));
    
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var moneyParameter = money.HasValue ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(decimal));
    
            var periodParameter = period != null ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Installement", contractnumParameter, project_idParameter, moneyParameter, periodParameter);
        }
    
        public virtual int Insert_Installement_Document(string name, string type, Nullable<int> total, string contract_num, Nullable<int> installment)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(int));
    
            var contract_numParameter = contract_num != null ?
                new ObjectParameter("contract_num", contract_num) :
                new ObjectParameter("contract_num", typeof(string));
    
            var installmentParameter = installment.HasValue ?
                new ObjectParameter("installment", installment) :
                new ObjectParameter("installment", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Installement_Document", nameParameter, typeParameter, totalParameter, contract_numParameter, installmentParameter);
        }
    
        public virtual ObjectResult<NHA_GenForm_Result3> NHA_GenForm(Nullable<int> pID, Nullable<int> uID)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(int));
    
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("uID", uID) :
                new ObjectParameter("uID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_GenForm_Result3>("NHA_GenForm", pIDParameter, uIDParameter);
        }
    
        public virtual ObjectResult<NHA_GenForm_Meeting_Result3> NHA_GenForm_Meeting(Nullable<int> pID, Nullable<int> period)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_GenForm_Meeting_Result3>("NHA_GenForm_Meeting", pIDParameter, periodParameter);
        }
    
        public virtual ObjectResult<NHA_GenForm_State2_Result3> NHA_GenForm_State2(Nullable<int> pID, Nullable<int> uID)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(int));
    
            var uIDParameter = uID.HasValue ?
                new ObjectParameter("uID", uID) :
                new ObjectParameter("uID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_GenForm_State2_Result3>("NHA_GenForm_State2", pIDParameter, uIDParameter);
        }
    
        public virtual ObjectResult<NHA_GenForm_widen_Result3> NHA_GenForm_widen(Nullable<int> pID, Nullable<int> period)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_GenForm_widen_Result3>("NHA_GenForm_widen", pIDParameter, periodParameter);
        }
    
        public virtual int NHA_Save_Comment(Nullable<int> project_id, string comment)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NHA_Save_Comment", project_idParameter, commentParameter);
        }
    
        public virtual int Period_insert(Nullable<int> project_id, string money, Nullable<int> day_period, string date_period, string detail)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var moneyParameter = money != null ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(string));
    
            var day_periodParameter = day_period.HasValue ?
                new ObjectParameter("day_period", day_period) :
                new ObjectParameter("day_period", typeof(int));
    
            var date_periodParameter = date_period != null ?
                new ObjectParameter("date_period", date_period) :
                new ObjectParameter("date_period", typeof(string));
    
            var detailParameter = detail != null ?
                new ObjectParameter("detail", detail) :
                new ObjectParameter("detail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Period_insert", project_idParameter, moneyParameter, day_periodParameter, date_periodParameter, detailParameter);
        }
    
        public virtual int Period_insert2(Nullable<int> project_id, string money, string percent_money, Nullable<int> day_period, string date_period, string detail)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var moneyParameter = money != null ?
                new ObjectParameter("money", money) :
                new ObjectParameter("money", typeof(string));
    
            var percent_moneyParameter = percent_money != null ?
                new ObjectParameter("percent_money", percent_money) :
                new ObjectParameter("percent_money", typeof(string));
    
            var day_periodParameter = day_period.HasValue ?
                new ObjectParameter("day_period", day_period) :
                new ObjectParameter("day_period", typeof(int));
    
            var date_periodParameter = date_period != null ?
                new ObjectParameter("date_period", date_period) :
                new ObjectParameter("date_period", typeof(string));
    
            var detailParameter = detail != null ?
                new ObjectParameter("detail", detail) :
                new ObjectParameter("detail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Period_insert2", project_idParameter, moneyParameter, percent_moneyParameter, day_periodParameter, date_periodParameter, detailParameter);
        }
    
        public virtual ObjectResult<PM_Select_Project_Result3> PM_Select_Project(Nullable<int> user_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PM_Select_Project_Result3>("PM_Select_Project", user_idParameter);
        }
    
        public virtual int Project_Document_Insert(Nullable<int> project_id, string doc, string type, string number, string period)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var docParameter = doc != null ?
                new ObjectParameter("doc", doc) :
                new ObjectParameter("doc", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var numberParameter = number != null ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Project_Document_Insert", project_idParameter, docParameter, typeParameter, numberParameter, periodParameter);
        }
    
        public virtual ObjectResult<Project_Document_Select_Result3> Project_Document_Select(Nullable<int> project_id, string period)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var periodParameter = period != null ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Project_Document_Select_Result3>("Project_Document_Select", project_idParameter, periodParameter);
        }
    
        public virtual int ProjectCharacter_Create(Nullable<int> project_id, Nullable<int> user_id, string the_character)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var the_characterParameter = the_character != null ?
                new ObjectParameter("the_character", the_character) :
                new ObjectParameter("the_character", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProjectCharacter_Create", project_idParameter, user_idParameter, the_characterParameter);
        }
    
        public virtual int Researcher_Delete(Nullable<int> project_id, Nullable<int> re_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var re_idParameter = re_id.HasValue ?
                new ObjectParameter("re_id", re_id) :
                new ObjectParameter("re_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Researcher_Delete", project_idParameter, re_idParameter);
        }
    
        public virtual int Researcher_insert(Nullable<int> project_id, Nullable<int> re_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var re_idParameter = re_id.HasValue ?
                new ObjectParameter("re_id", re_id) :
                new ObjectParameter("re_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Researcher_insert", project_idParameter, re_idParameter);
        }
    
        public virtual ObjectResult<Researcher_Select_Result3> Researcher_Select(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Researcher_Select_Result3>("Researcher_Select", pidParameter);
        }
    
        public virtual ObjectResult<Researcher_Select_Detail_Result3> Researcher_Select_Detail(Nullable<int> rid)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Researcher_Select_Detail_Result3>("Researcher_Select_Detail", ridParameter);
        }
    
        public virtual ObjectResult<Search_Researcher_Result3> Search_Researcher(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Researcher_Result3>("Search_Researcher", searchParameter);
        }
    
        public virtual ObjectResult<Select_Contract_Result3> Select_Contract(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Contract_Result3>("Select_Contract", project_idParameter);
        }
    
        public virtual ObjectResult<Select_Period_Result3> Select_Period(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Period_Result3>("Select_Period", project_idParameter);
        }
    
        public virtual ObjectResult<Select_Period_DateMoney_Result3> Select_Period_DateMoney(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Period_DateMoney_Result3>("Select_Period_DateMoney", project_idParameter);
        }
    
        public virtual ObjectResult<Select_Project_Result3> Select_Project(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Project_Result3>("Select_Project", project_idParameter);
        }
    
        public virtual ObjectResult<SelectCommit_NHA_Result3> SelectCommit_NHA(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCommit_NHA_Result3>("SelectCommit_NHA", pidParameter);
        }
    
        public virtual ObjectResult<SelectCommit_PM_Result3> SelectCommit_PM(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCommit_PM_Result3>("SelectCommit_PM", pidParameter);
        }
    
        public virtual ObjectResult<SelectMyProject_Result3> SelectMyProject(Nullable<int> uid)
        {
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMyProject_Result3>("SelectMyProject", uidParameter);
        }
    
        public virtual int SelectMyProject_NHA(Nullable<int> pid, Nullable<int> uid, ObjectParameter result)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectMyProject_NHA", pidParameter, uidParameter, result);
        }
    
        public virtual int SelectMyProject_PM(Nullable<int> pid, Nullable<int> uid, ObjectParameter result)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            var uidParameter = uid.HasValue ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SelectMyProject_PM", pidParameter, uidParameter, result);
        }
    
        public virtual ObjectResult<SP_BudgetPlan_Create_Report_Result3> SP_BudgetPlan_Create_Report(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BudgetPlan_Create_Report_Result3>("SP_BudgetPlan_Create_Report", yearParameter);
        }
    
        public virtual int SP_SuperPowerAdmin_Budget_Create(Nullable<int> year, Nullable<decimal> budget, ObjectParameter result)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var budgetParameter = budget.HasValue ?
                new ObjectParameter("budget", budget) :
                new ObjectParameter("budget", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuperPowerAdmin_Budget_Create", yearParameter, budgetParameter, result);
        }
    
        public virtual ObjectResult<SP_SuperPowerAdmin_Budget_Select_Result3> SP_SuperPowerAdmin_Budget_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SuperPowerAdmin_Budget_Select_Result3>("SP_SuperPowerAdmin_Budget_Select");
        }
    
        public virtual int SP_SuperPowerAdmin_Budget_Update(Nullable<int> year, Nullable<decimal> budget)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var budgetParameter = budget.HasValue ?
                new ObjectParameter("Budget", budget) :
                new ObjectParameter("Budget", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuperPowerAdmin_Budget_Update", yearParameter, budgetParameter);
        }
    
        public virtual int SP_SuperPowerAdmin_Budgetplan_Create(Nullable<int> project_id, Nullable<int> year, Nullable<decimal> january, Nullable<decimal> february, Nullable<decimal> march, Nullable<decimal> april, Nullable<decimal> may, Nullable<decimal> june, Nullable<decimal> july, Nullable<decimal> august, Nullable<decimal> september, Nullable<decimal> october, Nullable<decimal> november, Nullable<decimal> december)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var januaryParameter = january.HasValue ?
                new ObjectParameter("january", january) :
                new ObjectParameter("january", typeof(decimal));
    
            var februaryParameter = february.HasValue ?
                new ObjectParameter("february", february) :
                new ObjectParameter("february", typeof(decimal));
    
            var marchParameter = march.HasValue ?
                new ObjectParameter("march", march) :
                new ObjectParameter("march", typeof(decimal));
    
            var aprilParameter = april.HasValue ?
                new ObjectParameter("april", april) :
                new ObjectParameter("april", typeof(decimal));
    
            var mayParameter = may.HasValue ?
                new ObjectParameter("may", may) :
                new ObjectParameter("may", typeof(decimal));
    
            var juneParameter = june.HasValue ?
                new ObjectParameter("june", june) :
                new ObjectParameter("june", typeof(decimal));
    
            var julyParameter = july.HasValue ?
                new ObjectParameter("july", july) :
                new ObjectParameter("july", typeof(decimal));
    
            var augustParameter = august.HasValue ?
                new ObjectParameter("august", august) :
                new ObjectParameter("august", typeof(decimal));
    
            var septemberParameter = september.HasValue ?
                new ObjectParameter("september", september) :
                new ObjectParameter("september", typeof(decimal));
    
            var octoberParameter = october.HasValue ?
                new ObjectParameter("october", october) :
                new ObjectParameter("october", typeof(decimal));
    
            var novemberParameter = november.HasValue ?
                new ObjectParameter("november", november) :
                new ObjectParameter("november", typeof(decimal));
    
            var decemberParameter = december.HasValue ?
                new ObjectParameter("december", december) :
                new ObjectParameter("december", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuperPowerAdmin_Budgetplan_Create", project_idParameter, yearParameter, januaryParameter, februaryParameter, marchParameter, aprilParameter, mayParameter, juneParameter, julyParameter, augustParameter, septemberParameter, octoberParameter, novemberParameter, decemberParameter);
        }
    
        public virtual ObjectResult<SP_SuperPowerAdmin_ProjectInfo_Create_Result3> SP_SuperPowerAdmin_ProjectInfo_Create(string project_name, Nullable<int> year, Nullable<int> project_state, Nullable<int> project_period, Nullable<int> project_budget_year1, Nullable<int> project_budget_year2, Nullable<int> project_budget_year3, Nullable<int> project_budget_year4, Nullable<decimal> project_budget1, Nullable<decimal> project_budget2, Nullable<decimal> project_budget3, Nullable<decimal> project_budget4)
        {
            var project_nameParameter = project_name != null ?
                new ObjectParameter("project_name", project_name) :
                new ObjectParameter("project_name", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var project_stateParameter = project_state.HasValue ?
                new ObjectParameter("project_state", project_state) :
                new ObjectParameter("project_state", typeof(int));
    
            var project_periodParameter = project_period.HasValue ?
                new ObjectParameter("project_period", project_period) :
                new ObjectParameter("project_period", typeof(int));
    
            var project_budget_year1Parameter = project_budget_year1.HasValue ?
                new ObjectParameter("project_budget_year1", project_budget_year1) :
                new ObjectParameter("project_budget_year1", typeof(int));
    
            var project_budget_year2Parameter = project_budget_year2.HasValue ?
                new ObjectParameter("project_budget_year2", project_budget_year2) :
                new ObjectParameter("project_budget_year2", typeof(int));
    
            var project_budget_year3Parameter = project_budget_year3.HasValue ?
                new ObjectParameter("project_budget_year3", project_budget_year3) :
                new ObjectParameter("project_budget_year3", typeof(int));
    
            var project_budget_year4Parameter = project_budget_year4.HasValue ?
                new ObjectParameter("project_budget_year4", project_budget_year4) :
                new ObjectParameter("project_budget_year4", typeof(int));
    
            var project_budget1Parameter = project_budget1.HasValue ?
                new ObjectParameter("project_budget1", project_budget1) :
                new ObjectParameter("project_budget1", typeof(decimal));
    
            var project_budget2Parameter = project_budget2.HasValue ?
                new ObjectParameter("project_budget2", project_budget2) :
                new ObjectParameter("project_budget2", typeof(decimal));
    
            var project_budget3Parameter = project_budget3.HasValue ?
                new ObjectParameter("project_budget3", project_budget3) :
                new ObjectParameter("project_budget3", typeof(decimal));
    
            var project_budget4Parameter = project_budget4.HasValue ?
                new ObjectParameter("project_budget4", project_budget4) :
                new ObjectParameter("project_budget4", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SuperPowerAdmin_ProjectInfo_Create_Result3>("SP_SuperPowerAdmin_ProjectInfo_Create", project_nameParameter, yearParameter, project_stateParameter, project_periodParameter, project_budget_year1Parameter, project_budget_year2Parameter, project_budget_year3Parameter, project_budget_year4Parameter, project_budget1Parameter, project_budget2Parameter, project_budget3Parameter, project_budget4Parameter);
        }
    
        public virtual ObjectResult<SP_SuperPowerAdmin_SearchUser_Result3> SP_SuperPowerAdmin_SearchUser(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SuperPowerAdmin_SearchUser_Result3>("SP_SuperPowerAdmin_SearchUser", searchParameter);
        }
    
        public virtual ObjectResult<SP_User_Login_Result3> SP_User_Login(string user_name, string user_password)
        {
            var user_nameParameter = user_name != null ?
                new ObjectParameter("user_name", user_name) :
                new ObjectParameter("user_name", typeof(string));
    
            var user_passwordParameter = user_password != null ?
                new ObjectParameter("user_password", user_password) :
                new ObjectParameter("user_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_User_Login_Result3>("SP_User_Login", user_nameParameter, user_passwordParameter);
        }
    
        public virtual int Update_Project_State(Nullable<int> user_id, Nullable<int> project_id, Nullable<int> state)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Project_State", user_idParameter, project_idParameter, stateParameter);
        }
    
        public virtual int Upload_TOR_History(Nullable<int> user_id, Nullable<int> project_id, string number, string topic, string date, string detail)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var numberParameter = number != null ?
                new ObjectParameter("number", number) :
                new ObjectParameter("number", typeof(string));
    
            var topicParameter = topic != null ?
                new ObjectParameter("topic", topic) :
                new ObjectParameter("topic", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var detailParameter = detail != null ?
                new ObjectParameter("detail", detail) :
                new ObjectParameter("detail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Upload_TOR_History", user_idParameter, project_idParameter, numberParameter, topicParameter, dateParameter, detailParameter);
        }
    
        public virtual int UploadFile(Nullable<int> user_id, Nullable<int> project_id, string filename, string content, byte[] size, Nullable<int> state)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var filenameParameter = filename != null ?
                new ObjectParameter("filename", filename) :
                new ObjectParameter("filename", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("content", content) :
                new ObjectParameter("content", typeof(string));
    
            var sizeParameter = size != null ?
                new ObjectParameter("size", size) :
                new ObjectParameter("size", typeof(byte[]));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UploadFile", user_idParameter, project_idParameter, filenameParameter, contentParameter, sizeParameter, stateParameter);
        }
    
        public virtual ObjectResult<Budget_Select_TEST_Result> Budget_Select_TEST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Budget_Select_TEST_Result>("Budget_Select_TEST");
        }
    
        public virtual int SP_SuperPowerAdmin_Budget_Delete(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SuperPowerAdmin_Budget_Delete", yearParameter);
        }
    
        public virtual ObjectResult<SP_SuperPowerAdmin_Budget_SelectForUpdate_Result> SP_SuperPowerAdmin_Budget_SelectForUpdate(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SuperPowerAdmin_Budget_SelectForUpdate_Result>("SP_SuperPowerAdmin_Budget_SelectForUpdate", yearParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_SuperPowerAdmin_Budget_SelectTest(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_SuperPowerAdmin_Budget_SelectTest", yearParameter);
        }
    
        public virtual int Researcher_Edit(Nullable<int> rid, string role, string pname, string fname, string lname, string position, string institution, string idcard, string birth, string gender, string education, string degree, string major, string experience, string tel, string fax, string phone, string email)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            var pnameParameter = pname != null ?
                new ObjectParameter("pname", pname) :
                new ObjectParameter("pname", typeof(string));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("position", position) :
                new ObjectParameter("position", typeof(string));
    
            var institutionParameter = institution != null ?
                new ObjectParameter("institution", institution) :
                new ObjectParameter("institution", typeof(string));
    
            var idcardParameter = idcard != null ?
                new ObjectParameter("idcard", idcard) :
                new ObjectParameter("idcard", typeof(string));
    
            var birthParameter = birth != null ?
                new ObjectParameter("birth", birth) :
                new ObjectParameter("birth", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var educationParameter = education != null ?
                new ObjectParameter("education", education) :
                new ObjectParameter("education", typeof(string));
    
            var degreeParameter = degree != null ?
                new ObjectParameter("Degree", degree) :
                new ObjectParameter("Degree", typeof(string));
    
            var majorParameter = major != null ?
                new ObjectParameter("major", major) :
                new ObjectParameter("major", typeof(string));
    
            var experienceParameter = experience != null ?
                new ObjectParameter("experience", experience) :
                new ObjectParameter("experience", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Researcher_Edit", ridParameter, roleParameter, pnameParameter, fnameParameter, lnameParameter, positionParameter, institutionParameter, idcardParameter, birthParameter, genderParameter, educationParameter, degreeParameter, majorParameter, experienceParameter, telParameter, faxParameter, phoneParameter, emailParameter);
        }
    
        public virtual int Project_Document_Delete(Nullable<int> project_id, string docName, string period)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var docNameParameter = docName != null ?
                new ObjectParameter("docName", docName) :
                new ObjectParameter("docName", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Project_Document_Delete", project_idParameter, docNameParameter, periodParameter);
        }
    
        public virtual int FromToAt_insert(Nullable<int> project_id, string state, string from, string to, string at, string date)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var fromParameter = from != null ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(string));
    
            var toParameter = to != null ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(string));
    
            var atParameter = at != null ?
                new ObjectParameter("at", at) :
                new ObjectParameter("at", typeof(string));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FromToAt_insert", project_idParameter, stateParameter, fromParameter, toParameter, atParameter, dateParameter);
        }
    
        public virtual int Project_abstract(Nullable<int> project_id, string @abstract)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var abstractParameter = @abstract != null ?
                new ObjectParameter("abstract", @abstract) :
                new ObjectParameter("abstract", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Project_abstract", project_idParameter, abstractParameter);
        }
    
        public virtual ObjectResult<SP_BudgetPlan_Select_Report_Result> SP_BudgetPlan_Select_Report(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BudgetPlan_Select_Report_Result>("SP_BudgetPlan_Select_Report", yearParameter);
        }
    
        public virtual ObjectResult<Project_SelectAbstract_Result> Project_SelectAbstract(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Project_SelectAbstract_Result>("Project_SelectAbstract", project_idParameter);
        }
    
        public virtual int ProjectPublishFileUpload_Create(Nullable<int> project_id, string nameFomTextBox, string filename, string type)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var nameFomTextBoxParameter = nameFomTextBox != null ?
                new ObjectParameter("nameFomTextBox", nameFomTextBox) :
                new ObjectParameter("nameFomTextBox", typeof(string));
    
            var filenameParameter = filename != null ?
                new ObjectParameter("filename", filename) :
                new ObjectParameter("filename", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProjectPublishFileUpload_Create", project_idParameter, nameFomTextBoxParameter, filenameParameter, typeParameter);
        }
    
        public virtual int ProjectPublishFileUpload_Delete(Nullable<int> file_id)
        {
            var file_idParameter = file_id.HasValue ?
                new ObjectParameter("file_id", file_id) :
                new ObjectParameter("file_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProjectPublishFileUpload_Delete", file_idParameter);
        }
    
        public virtual ObjectResult<SP_BudgetPlan_Create_Report_get_Allocate_Result> SP_BudgetPlan_Create_Report_get_Allocate(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BudgetPlan_Create_Report_get_Allocate_Result>("SP_BudgetPlan_Create_Report_get_Allocate", yearParameter);
        }
    
        public virtual ObjectResult<ProjectPublishFileType_Select_Result> ProjectPublishFileType_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProjectPublishFileType_Select_Result>("ProjectPublishFileType_Select");
        }
    
        public virtual ObjectResult<ProjectPublishFileUpload_Select_Result> ProjectPublishFileUpload_Select(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProjectPublishFileUpload_Select_Result>("ProjectPublishFileUpload_Select", project_idParameter);
        }
    
        public virtual int ProjectPublishFilePermission_Update(Nullable<int> project_id, Nullable<int> file_id, string status)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var file_idParameter = file_id.HasValue ?
                new ObjectParameter("file_id", file_id) :
                new ObjectParameter("file_id", typeof(int));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProjectPublishFilePermission_Update", project_idParameter, file_idParameter, statusParameter);
        }
    
        public virtual ObjectResult<ProjectPublishFileUpload_SelectDownload_Result> ProjectPublishFileUpload_SelectDownload(Nullable<int> file_id)
        {
            var file_idParameter = file_id.HasValue ?
                new ObjectParameter("file_id", file_id) :
                new ObjectParameter("file_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProjectPublishFileUpload_SelectDownload_Result>("ProjectPublishFileUpload_SelectDownload", file_idParameter);
        }
    
        public virtual int ProjectCharacter_Delete(Nullable<int> project_id, Nullable<int> user_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProjectCharacter_Delete", project_idParameter, user_idParameter);
        }
    
        public virtual ObjectResult<Select_BudgetForCheck_Result> Select_BudgetForCheck(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_BudgetForCheck_Result>("Select_BudgetForCheck", project_idParameter);
        }
    
        public virtual ObjectResult<NHA_GenForm_Meeting1_Result1> NHA_GenForm_Meeting1(Nullable<int> pID, Nullable<int> period)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_GenForm_Meeting1_Result1>("NHA_GenForm_Meeting1", pIDParameter, periodParameter);
        }
    
        public virtual ObjectResult<NHA_GenForm_widen1_Result1> NHA_GenForm_widen1(Nullable<int> pID, Nullable<int> period)
        {
            var pIDParameter = pID.HasValue ?
                new ObjectParameter("pID", pID) :
                new ObjectParameter("pID", typeof(int));
    
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_GenForm_widen1_Result1>("NHA_GenForm_widen1", pIDParameter, periodParameter);
        }
    
        public virtual int Project_abstract1(Nullable<int> project_id, string @abstract)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            var abstractParameter = @abstract != null ?
                new ObjectParameter("abstract", @abstract) :
                new ObjectParameter("abstract", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Project_abstract1", project_idParameter, abstractParameter);
        }
    
        public virtual ObjectResult<string> Project_SelectAbstract1(Nullable<int> project_id)
        {
            var project_idParameter = project_id.HasValue ?
                new ObjectParameter("project_id", project_id) :
                new ObjectParameter("project_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Project_SelectAbstract1", project_idParameter);
        }
    
        public virtual int Researcher_Edit1(Nullable<int> rid, string role, string pname, string fname, string lname, string position, string institution, string idcard, string birth, string gender, string education, string degree, string major, string experience, string tel, string fax, string phone, string email)
        {
            var ridParameter = rid.HasValue ?
                new ObjectParameter("rid", rid) :
                new ObjectParameter("rid", typeof(int));
    
            var roleParameter = role != null ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(string));
    
            var pnameParameter = pname != null ?
                new ObjectParameter("pname", pname) :
                new ObjectParameter("pname", typeof(string));
    
            var fnameParameter = fname != null ?
                new ObjectParameter("fname", fname) :
                new ObjectParameter("fname", typeof(string));
    
            var lnameParameter = lname != null ?
                new ObjectParameter("lname", lname) :
                new ObjectParameter("lname", typeof(string));
    
            var positionParameter = position != null ?
                new ObjectParameter("position", position) :
                new ObjectParameter("position", typeof(string));
    
            var institutionParameter = institution != null ?
                new ObjectParameter("institution", institution) :
                new ObjectParameter("institution", typeof(string));
    
            var idcardParameter = idcard != null ?
                new ObjectParameter("idcard", idcard) :
                new ObjectParameter("idcard", typeof(string));
    
            var birthParameter = birth != null ?
                new ObjectParameter("birth", birth) :
                new ObjectParameter("birth", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(string));
    
            var educationParameter = education != null ?
                new ObjectParameter("education", education) :
                new ObjectParameter("education", typeof(string));
    
            var degreeParameter = degree != null ?
                new ObjectParameter("Degree", degree) :
                new ObjectParameter("Degree", typeof(string));
    
            var majorParameter = major != null ?
                new ObjectParameter("major", major) :
                new ObjectParameter("major", typeof(string));
    
            var experienceParameter = experience != null ?
                new ObjectParameter("experience", experience) :
                new ObjectParameter("experience", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var faxParameter = fax != null ?
                new ObjectParameter("fax", fax) :
                new ObjectParameter("fax", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Researcher_Edit1", ridParameter, roleParameter, pnameParameter, fnameParameter, lnameParameter, positionParameter, institutionParameter, idcardParameter, birthParameter, genderParameter, educationParameter, degreeParameter, majorParameter, experienceParameter, telParameter, faxParameter, phoneParameter, emailParameter);
        }
    }
}
