//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    
    public partial class NHA_GenForm_State2_Result1
    {
        public string project_name { get; set; }
        public Nullable<int> period { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<decimal> project_budget { get; set; }
    }
}
