//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    
    public partial class Select_Contract_Result3
    {
        public string contract_id { get; set; }
        public string day_contract { get; set; }
        public string comment { get; set; }
        public int order { get; set; }
        public Nullable<int> project_id { get; set; }
        public string day_start { get; set; }
        public string day_end { get; set; }
        public string Employee { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<decimal> Contract_Money { get; set; }
    }
}
