//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    
    public partial class Select_Period_DateMoney_Result3
    {
        public string day_contract { get; set; }
        public Nullable<decimal> project_budget { get; set; }
    }
}
