//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Data
{
    using System;
    
    public partial class SelectCommit_NHA_Result3
    {
        public string pname { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> user_id { get; set; }
    }
}
